/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SeoAuditRouteImport } from './routes/seo-audit'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as TechnicalReviewRouteImport } from './routes/technical-review'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as WhyRycodeRouteImport } from './routes/why-rycode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoAuditRoute = SeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalReviewRoute = TechnicalReviewRouteImport.update({
  id: '/technical-review',
  path: '/technical-review',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRycodeRoute = WhyRycodeRouteImport.update({
  id: '/why-rycode',
  path: '/why-rycode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/seo-audit': typeof SeoAuditRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/technical-review': typeof TechnicalReviewRoute
  '/technologies': typeof TechnologiesRoute
  '/why-rycode': typeof WhyRycodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/seo-audit': typeof SeoAuditRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/technical-review': typeof TechnicalReviewRoute
  '/technologies': typeof TechnologiesRoute
  '/why-rycode': typeof WhyRycodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/problems': typeof ProblemsRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/seo-audit': typeof SeoAuditRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/technical-review': typeof TechnicalReviewRoute
  '/technologies': typeof TechnologiesRoute
  '/why-rycode': typeof WhyRycodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/login'
    | '/problems'
    | '/process'
    | '/projects'
    | '/seo-audit'
    | '/services'
    | '/solutions'
    | '/start-project'
    | '/technical-review'
    | '/technologies'
    | '/why-rycode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/login'
    | '/problems'
    | '/process'
    | '/projects'
    | '/seo-audit'
    | '/services'
    | '/solutions'
    | '/start-project'
    | '/technical-review'
    | '/technologies'
    | '/why-rycode'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/login'
    | '/problems'
    | '/process'
    | '/projects'
    | '/seo-audit'
    | '/services'
    | '/solutions'
    | '/start-project'
    | '/technical-review'
    | '/technologies'
    | '/why-rycode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  ProblemsRoute: typeof ProblemsRoute
  ProcessRoute: typeof ProcessRoute
  ProjectsRoute: typeof ProjectsRoute
  SeoAuditRoute: typeof SeoAuditRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  StartProjectRoute: typeof StartProjectRoute
  TechnicalReviewRoute: typeof TechnicalReviewRoute
  TechnologiesRoute: typeof TechnologiesRoute
  WhyRycodeRoute: typeof WhyRycodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-audit': {
      id: '/seo-audit'
      path: '/seo-audit'
      fullPath: '/seo-audit'
      preLoaderRoute: typeof SeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-review': {
      id: '/technical-review'
      path: '/technical-review'
      fullPath: '/technical-review'
      preLoaderRoute: typeof TechnicalReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-rycode': {
      id: '/why-rycode'
      path: '/why-rycode'
      fullPath: '/why-rycode'
      preLoaderRoute: typeof WhyRycodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  ProblemsRoute: ProblemsRoute,
  ProcessRoute: ProcessRoute,
  ProjectsRoute: ProjectsRoute,
  SeoAuditRoute: SeoAuditRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRoute,
  StartProjectRoute: StartProjectRoute,
  TechnicalReviewRoute: TechnicalReviewRoute,
  TechnologiesRoute: TechnologiesRoute,
  WhyRycodeRoute: WhyRycodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
